console.log("")
console.log("   ")
console.log("")
console.log("")
console.log("   ")
console.log("   |   |    |```  |    |      ' '    |")
console.log("   |---|    |---  |    |    '     '  |")
console.log("   |   |    |___  |___ |___  ' _ '   O")
console.log("")
console.log("")
console.log("")
console.log("")
console.log("")
console.log("")
console.log("   Visit http://kevinmircovich.com/  ")
console.log("")
console.log("")
console.log("")
console.log("")
console.log("")
console.log("")
console.log("")
console.log("")
console.log("")